version: "3.3"
services:
  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: nginx
    restart: unless-stopped
    links:
      - php
    networks:
      - nginx
    ports:
      - "5555:80"   # http
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOGS}:/var/log/nginx
      - ${NGINX_WEB}:/media
      - ${NGINX_SSL_CERTS}:/etc/ssl
  php:
    image: php:7-fpm
    volumes:
      - ${NGINX_WEB}:/media
    networks:
      - nginx
    restart: unless-stopped
    container_name: php

networks:
  nginx:
    driver: bridge