version: '3'
services:
  certbot:
    container_name: certbot
    build: github.com/buzz/certbot
    restart: always
    depends_on:
      - nginx
    volumes:
      - ./volumes/www/acme-challenges:/var/www/acme-challenges
      - ./volumes/etc/letsencrypt:/etc/letsencrypt
    environment:
      - DOMAINS=roshamagin.ru
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 9080:80
      - 9443:443
    volumes:
      - ./volumes/www:/var/www
      - ./volumes/etc/nginx:/etc/nginx:ro
      - ./volumes/etc/letsencrypt:/etc/letsencrypt:ro