version: "3.9"
services:
  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: nginx
    restart: unless-stopped
    networks:
      - nginx
    ports:
      - "8443:443"   # https
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOGS}:/var/log/nginx

networks:
  jenkins:
    name: nginx
    driver: bridge